DROP TABLE IF EXISTS hospitals.diabetes ;

CREATE TABLE hospitals.diabetes (
encounter_id int,
patient_nbr int,
race text,
gender text,
age text ,
weight text,
admission_type_id int,
discharge_disposition_id int,
admission_source_id  int,
time_in_hospital int,
payer_code text,
medical_specialty text,
num_lab_procedures int,
num_procedures	 int ,
num_medications int,
number_outpatient int,
number_emergency int,
number_inpatient int,
diag_1 text,
diag_2 text,
diag_3 text,
number_diagnoses int,
max_glu_serum text,
A1Cresult text,
metformin text,
repaglinide text,
nateglinide text,
chlorpropamide text,
glimepiride text,
acetohexamide text,
glipizide text,
glyburide text,
tolbutamide text,
pioglitazone text,
rosiglitazone text,
acarbose text,
miglitol text,
troglitazone text,
tolazamide text,
examide text,
citoglipton text,
insulin text,
glyburide_metformin text,
glipizide_metformin text,
glimepiride_pioglitazone text,
metformin_rosiglitazone text,
metformin_pioglitazone text,
any_change text,
diabetesMed text,
readmitted text
);

LOAD DATA
INFILE  "/Users/geoffrey.kip/Projects/uci_diabetes/data/diabetic_data.csv"
INTO TABLE hospitals.diabetes
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(    encounter_id ,
patient_nbr ,
race ,
gender ,
age  ,
weight ,
admission_type_id ,
discharge_disposition_id ,
admission_source_id  ,
time_in_hospital ,
payer_code ,
medical_specialty ,
num_lab_procedures ,
num_procedures	  ,
num_medications ,
number_outpatient ,
number_emergency ,
number_inpatient ,
diag_1 ,
diag_2 ,
diag_3 ,
number_diagnoses ,
max_glu_serum ,
A1Cresult ,
metformin ,
repaglinide ,
nateglinide ,
chlorpropamide ,
glimepiride ,
acetohexamide ,
glipizide ,
glyburide ,
tolbutamide ,
pioglitazone ,
rosiglitazone ,
acarbose ,
miglitol ,
troglitazone ,
tolazamide ,
examide ,
citoglipton ,
insulin ,
glyburide_metformin ,
glipizide_metformin ,
glimepiride_pioglitazone ,
metformin_rosiglitazone ,
metformin_pioglitazone ,
any_change ,
diabetesMed ,
readmitted
);
